import asyncio
import os
import subprocess
from tempfile import TemporaryDirectory
from typing import Tuple
from agents.utils import save_log

async def run_tests(code: str, tests: str) -> Tuple[bool, str]:
    """
    Simulate a complete code + test run using a temporary directory.

    Files written:
      user_code.py       <- FastAPI service generated by code_agent
      test_user_code.py  <- pytest tests generated by test_agent

    Then we run pytest and return (success, report).
    """
    print("[run_agent] Writing code and tests to temporary directory and running pytest...")
    await asyncio.sleep(0.1)

    with TemporaryDirectory() as tmpdir:
        user_code_path = os.path.join(tmpdir, "user_code.py")
        test_path = os.path.join(tmpdir, "test_user_code.py")

        with open(user_code_path, "w", encoding="utf-8") as f:
            f.write(code)

        with open(test_path, "w", encoding="utf-8") as f:
            f.write(tests)

        try:
            result = subprocess.run(
                ["pytest", "-q"],
                cwd=tmpdir,
                capture_output=True,
                text=True,
                timeout=20,
            )
            success = result.returncode == 0
            stdout = result.stdout or ""
            stderr = result.stderr or ""
            report = stdout + "\n" + stderr

            print("[run_agent] Pytest finished. Success:", success)
            save_log(report, "pytest.log")
            return success, report
        except Exception as e:
            error_msg = f"Exception during pytest run: {e}"
            print("[run_agent]", error_msg)
            save_log(error_msg, "pytest.log")
            return False, error_msg
